name: Auto Label Conflicts
on: [pull_request_target]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v1.2.5
        with:
          conflict_label_name: "nEeDs tO lEaRn giT"
          github_token: ${{ github.token }}

          # --- Optional Inputs ---
          # To make sure the merge commit exactly matches the branch
          detect_merge_changes: false # or true to handle as conflicts
          # Omitting `conflict_comment` will disable commenting, only the label will be applied
          # The optional `${author}` will be replaced with the username of the pull request
          conflict_comment: |
            :wave: Hi, @${author}, you suck.

#       - name: weekly-pull-requests-closure
#         uses: kyslik/close-pull-requests-based-on-label@v1.0.0
#         env:
#           LABEL: "nEeDs tO lEaRn giT"
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Better not erase your hard drive :)
          reactions: '-1'
      - name: Close Pull
        uses: peter-evans/close-pull@v2.0.0
        with:
          comment: |
            :wave: Hi, @${author}, better not wipe your hard drive.
          delete-branch: true
